spring:
  redis:
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 10
        max-wait: -1
        min-idle: 2
    password: ''
    port: 6379
    timeout: 6000
    database: 1
server:
  port: 8008
